language: cpp

os:
  - linux
  - osx

compiler:
  - clang++
  - g++

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8.2

branches:
  only:
    - master
    - dev

env:
  - BUILD_CXX_STANDARD="11"
  - BUILD_CXX_STANDARD="14"
  global:
    - CI_HOME=`pwd`

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - george-edison55-precise-backports
    packages:
      - gcc-5
      - g++-5
      - clang-3.9
      - cmake
      - cmake-data

install:
  - pip install --user cpp-coveralls
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - cd $CI_HOME
  - mkdir build && cd build
  - cmake -DRPCLIB_ENABLE_COVERAGE=ON -DRPCLIB_BUILD_TESTS=ON -DRPCLIB_CXX_STANDARD=$BUILD_CXX_STANDARD ..
  - make -j2

after_success:
  - ./build/output/bin/rpc_test
  - coveralls --exclude dependencies --exclude test --exclude include/rpc/msgpack --exclude include/rcp/msgpack.hpp --gcov /usr/bin/gcov-5


