dist: trusty
language: cpp
compiler:
    - clang-3.7

env:
    global:
        - CI_HOME=`pwd`

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
        packages:
            - clang-3.7

script:
    - cd $CI_HOME
    - git submodule init
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake ..
    - make -j2
    - ./tests/callme_test



