sudo: required
dist: trusty
language: cpp

env:
  global:
    - CI_HOME=`pwd`

before_install:
    - sudo apt-get update
    - sudo apt-get -y install libgtest-dev google-mock libuv-dev libboost-dev
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
    - cd $CI_HOME


script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ./tests/callme_test

install: true # skipped


