dist: trusty
language: cpp
compiler:
    - clang-3.7

env:
    global:
        - CI_HOME=`pwd`

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
        packages:
            - clang-3.7
            - cmake

install:
#Use the latest clang if we're compiling with clang
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
    - cd $CI_HOME
    - git submodule init
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake ..
    - make -j2
    - ./tests/callme_test



