dist: trusty
language: cpp
compiler:
    - clang

env:
    global:
        - CI_HOME=`pwd`

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
        packages:
            - clang-3.7
            - cmake
            - cmake-data

install:
    - pip install --user codecov
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
    - cd $CI_HOME
    - git submodule init
    - git submodule update --init --recursive
    - mkdir build && cd build
    - cmake -Dcoverage=ON ..
    - make -j2

after_success:
    - ./tests/callme_test
    - find /home/travis/build/sztomi/callme -type f -name '*.gcno'
    - codecov

