sudo: required
dist: trusty
language: cpp

before_install:
    - sudo apt-get update
    - sudo apt-get -y install google-mock libuv-dev libboost-dev
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"


script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ./tests/callme_test

install: true # skipped


