dist: trusty
language: cpp
compiler:
  #- clang
  - g++

branches:
  only:
    - master
    - dev

env:
  global:
    - CI_HOME=`pwd`

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports
    packages:
      - gcc-5
      - g++-5
      - cmake
      - cmake-data

install:
  - pip install --user cpp-coveralls
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
  - cd $CI_HOME
  - git submodule init
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake -DRPCLIB_ENABLE_COVERAGE=ON -DRPCLIB_BUILD_TESTS=ON ..
  - make -j2

after_success:
  - ./output/bin/rpc_test
  - cd ..
  - coveralls --exclude dependencies --exclude test --exclude include/msgpack --exclude include/msgpack.hpp --gcov /usr/bin/gcov-5


