docs_dir: pages
site_name: rpclib

pages:
  - 'Home': 'index.md'
  - 'Guides':
    - 'Getting started': 'gettingstarted.md'
    - 'Primer': 'primer.md'
    - 'Cookbook': 'cookbook.md'
    - 'Glossary': 'glossary.md'
  - 'Advanced':
    - 'Building': 'building.md'
    - 'Internal design': 'design.md'
    - 'Specification': 'spec.md'

theme_dir: rpclib-flatly
extra_css: ['extra.css']

markdown_extensions:
  - toc:
      permalink: True
      baselevel: 1
  - admonition
  - fontawesome_markdown

