docs_dir: pages
site_name: rpclib

pages:
  - 'Home': 'index.md'
  - 'Getting started': 'gettingstarted.md'
  - 'Cookbook': 'cookbook.md'
  - 'Primer': 'primer.md'
  - 'Building': 'building.md'

theme_dir: rpclib-flatly
extra_css: ['extra.css']

markdown_extensions:
  - toc:
      permalink: True
      baselevel: 1
  - admonition
  - fontawesome_markdown

